In [1]:
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt

g:\Programok\Anaconda\envs\python_course\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [3]:
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

In [4]:
df.loc[:, 'salary_rate':'salary_hour_avg']

       salary_rate  salary_year_avg  salary_hour_avg
0              NaN              NaN              NaN
1              NaN              NaN              NaN
2              NaN              NaN              NaN
3              NaN              NaN              NaN
4              NaN              NaN              NaN
...            ...              ...              ...
785736         NaN              NaN              NaN
785737         NaN              NaN              NaN
785738         NaN              NaN              NaN
785739         NaN              NaN              NaN
785740         NaN              NaN              NaN

[785741 rows x 3 columns]

In [7]:
median_salary_year = df['salary_year_avg'].median()

In [8]:
median_salary_hour = df['salary_hour_avg'].median()

In [9]:
df_filled = df

In [13]:
df_filled['salary_year_avg'] = df_filled['salary_year_avg'].fillna(median_salary_year)
df_filled['salary_hour_avg'] = df_filled['salary_hour_avg'].fillna(median_salary_hour)

In [16]:
df_filled.loc[:10, 'salary_rate':'salary_hour_avg']

   salary_rate  salary_year_avg  salary_hour_avg
0          NaN         115000.0            45.98
1          NaN         115000.0            45.98
2          NaN         115000.0            45.98
3          NaN         115000.0            45.98
4          NaN         115000.0            45.98
5          NaN         115000.0            45.98
6          NaN         115000.0            45.98
7          NaN         115000.0            45.98
8          NaN         115000.0            45.98
9          NaN         115000.0            45.98
10         NaN         115000.0            45.98

In [19]:
df_unique = df_filled

df_unique = df_unique.drop_duplicates()

print('Length of original df       :', len(df_filled))
print('Length of drop duplicates df:', len(df_unique))
print('Rows dropped:                ', len(df_filled)-len(df_unique))

Length of original df       : 785741
Length of drop duplicates df: 785640
Rows dropped:                 101

In [22]:
df_unique = df_unique.drop_duplicates(subset=['job_title', 'company_name'])

print('Length of original df       :', len(df_filled))
print('Length of drop duplicates df:', len(df_unique))
print('Rows dropped:                ', len(df_filled)-len(df_unique))

Length of original df       : 785741
Length of drop duplicates df: 508042
Rows dropped:                 277699