In [1]:
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt

g:\Programok\Anaconda\envs\python_course\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [4]:
df.head()

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,NaN,NaN,NaN,Boehringer Ingelheim,NaN,NaN
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,NaN,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,NaN,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,NaN,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,NaN,NaN,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."

In [5]:
df.tail()

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
785736,Software Engineer,DevOps Engineer,Singapura,melalui Trabajo.org,Pekerjaan tetap,False,Singapore,2023-03-13 06:16:16,False,False,Singapore,NaN,NaN,NaN,CAREERSTAR INTERNATIONAL PTE. LTD.,"['bash', 'python', 'perl', 'linux', 'unix', 'k...","{'os': ['linux', 'unix'], 'other': ['kubernete..."
785737,Data Analyst,CRM Data Analyst,"Bad Rodach, Jerman",melalui BeBee Deutschland,Pekerjaan tetap,False,Germany,2023-03-12 06:18:18,False,False,Germany,NaN,NaN,NaN,HABA FAMILYGROUP,"['sas', 'sas', 'sql', 'excel']","{'analyst_tools': ['sas', 'excel'], 'programmi..."
785738,Business Analyst,Commercial Analyst - Start Now,Malaysia,melalui Ricebowl,Pekerjaan tetap,False,Malaysia,2023-03-12 06:32:36,False,False,Malaysia,NaN,NaN,NaN,Lendlease Corporation,"['powerpoint', 'excel']","{'analyst_tools': ['powerpoint', 'excel']}"
785739,Data Engineer,"Principal Associate, Data Engineer (Remote-Eli...","Newark, New Jersey, Amerika Serikat",melalui Recruit.net,Pekerjaan tetap,False,Sudan,2023-03-12 06:32:15,False,False,Sudan,NaN,NaN,NaN,Capital One,"['python', 'go', 'nosql', 'sql', 'mongo', 'she...","{'cloud': ['aws', 'snowflake', 'azure', 'redsh..."
785740,Software Engineer,AWS System Analyst,India,melalui Trigyn,Pekerjaan tetap,False,India,2023-03-13 06:16:31,False,False,India,NaN,NaN,NaN,Trigyn,"['aws', 'flow']","{'cloud': ['aws'], 'other': ['flow']}"

In [6]:
df.sample(10)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
279551,Data Scientist,Principal Data Scientist - HYBRID- Xumo,Anywhere,via ZipRecruiter,Full-time,True,"California, United States",2023-04-06 07:02:22,False,False,United States,NaN,NaN,NaN,Comcast,"['elixir', 'python', 'java', 'mysql', 'aws', '...","{'cloud': ['aws', 'azure'], 'databases': ['mys..."
8308,Data Engineer,Data Engineer. Job in Düsseldorf NBC4i Jobs,"Düsseldorf, Germany",via NBC4i Jobs,Full-time,False,Germany,2023-07-10 13:32:18,True,False,Germany,NaN,NaN,NaN,StepStone GmbH,NaN,NaN
762471,Data Analyst,Oncology Bioinformatics Genomic Data Analyst,"San Francisco, CA",via Dice,Contractor,False,"California, United States",2023-03-28 20:02:01,False,False,United States,hour,NaN,65.0,BayOne Solutions,['r'],{'programming': ['r']}
757116,Data Analyst,Data Analyst,"New York, NY",via LinkedIn,Contractor,False,"New York, United States",2023-09-19 19:59:57,False,False,United States,hour,NaN,30.0,24 Seven Talent,"['sql', 'word', 'powerpoint', 'tableau', 'excel']","{'analyst_tools': ['word', 'powerpoint', 'tabl..."
463211,Data Scientist,Data Scientist,"Tucker, GA",via Trabajo.org,Full-time,False,"Florida, United States",2023-05-06 14:05:18,False,False,United States,NaN,NaN,NaN,Rose International,"['sas', 'sas', 'sql']","{'analyst_tools': ['sas'], 'programming': ['sa..."
15605,Senior Data Engineer,BUSINESS DATA ANALYSTE Senior H/F,Luxembourg,via BeBee,Full-time,False,Luxembourg,2023-11-07 14:06:30,True,False,Luxembourg,NaN,NaN,NaN,Banque Internationale à Luxembourg (BIL),NaN,NaN
219847,Data Analyst,Data Analyst Staff - Level 4,"Fort Worth, TX",via Indeed,Full-time,False,"Texas, United States",2023-03-30 22:01:46,False,True,United States,NaN,NaN,NaN,Sikorsky Aircraft Corporation,"['python', 'r', 'sql', 'sap']","{'analyst_tools': ['sap'], 'programming': ['py..."
32664,Data Analyst,DATA ANALYST,"Ghent, Belgium",via VDAB,Full-time,False,Belgium,2023-08-07 14:24:52,True,False,Belgium,NaN,NaN,NaN,Blake & Partners,NaN,NaN
27435,Data Scientist,"Remote Data Scientist, Strategic Finance","Remote, OR",via BeBee,Full-time,False,"California, United States",2023-08-05 13:20:02,False,True,United States,NaN,NaN,NaN,Figma,"['sql', 'python', 'r', 'go', 'redshift', 'snow...","{'cloud': ['redshift', 'snowflake'], 'programm..."
430850,Data Scientist,Data Scientist,Anywhere,via LinkedIn,Full-time,True,"Texas, United States",2023-01-04 01:33:58,False,False,United States,NaN,NaN,NaN,bluebird bio,"['r', 'python']","{'programming': ['r', 'python']}"

In [8]:
dataset = load_dataset('lukebarousse/data_jobs')
df_original = dataset['train'].to_pandas()

In [9]:
df_altered = df_original.copy()

In [10]:
print('ID of df_original:              ', id(df_original))
print('ID of df_altered:               ', id(df_altered))
print('Are the two dataframes the same?', id(df_original) == id(df_altered))

ID of df_original:               1241966158672
ID of df_altered:                1241966159632
Are the two dataframes the same? False